export const SupabasePublicKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrdXJ4bGVydGlldmFhZXNleGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDY2NTc0NDYsImV4cCI6MTk2MjIzMzQ0Nn0.asuKI8uNTuNTQSbko6552j4cDsi8lEuKT2opCH1p4JM' as const;

export const SupabaseUrl = 'https://wkurxlertievaaesexbc.supabase.co' as const;
